dist: trusty
sudo: false
language: python
python:
  - 3.5
install:
  - pip install --upgrade setuptools pip
  - pip install --upgrade 'spacy<2.0'
  - python setup.py install
script: python setup.py test
